### ISSUE TITLE
Wrong next full moon

### ISSUE THREAD

**Issue by qstyler** [solarissmoke/php-moon-phase#10]
Hi!
I noticed that some times your script returns wrong next full moon.

Let's say we have a timestamp 1062009900. Which is Aug 27, 2003.

The moon phase for this date is New Moon and it's correct. But the result of the next full moon is 1065770899, which is Oct 10, 2003. And it makes it 43 days till the next full moon.

**Comment by solarissmoke** [comment]
Hi @qstyler,

I think the issue here is poor function naming on my part. `next_full_moon()` doesn't tell you when the next full moon is (sorry!), but when the full moon is in the **next lunar cycle**. For the full moon in the current cycle you need to use `full_moon()`.

If you supply a timestamp that is somewhere in between new moon and full moon, then `full_moon()` will give you the time of the full moon in the current cycle. `next_full_moon()` will give you the time of the full moon in the next cycle (hence your 43 day gap).

The timestamp you provided (1062009900) is: 27 Aug 03 18:45:00 +0000

The new moon on that date is at: Wed, 27 Aug 03 17:26:31 +0000 

So in this case `full_moon()` will give you the time of the full moon in this cycle: Sep 03 16:36:12 +0000. `next_full_moon()` will report the full moon in the *next* cycle: 10 Oct 03 07:28:19 +0000.

**Comment by qstyler** [comment]
Wow! Thanks!
