### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by madsenfr** [solarissmoke/php-moon-phase#23]
Hi,
I use this script for years to get time of the next new moon.
I tried to update to latest version and I get this error : 
`Parse error: syntax error, unexpected ':', expecting ';' or '{' in MoonPhase.php on line 149`
I run this Under EasyPHP with PHP version is 5.5.8 and online 5.6.34 whereas composer.json require php 5.3.0.
Any Idea ?

**Comment by solarissmoke** [comment]
I've updated the composer.json to reflect that the library requires PHP 7.2 or higher. You're getting an error because of syntax that was introduced in this version of PHP, which will not be understood in older versions.

Note that PHP 5.6 reached end of life in 2018 - I really would not recommend using it anywhere in production.
