### ISSUE TITLE
phase_name seems wrong

### ISSUE THREAD

**Issue by culbrique** [solarissmoke/php-moon-phase#25]
Hi
I'm using the phase_name function and this returns a wrong name, I'm always getting a day or two lag from the correct phase name.

```
setlocale(LC_TIME, "fr_FR");
date_default_timezone_set('Europe/Paris');
$moon = new Solaris\MoonPhase();
$moonphasename = $moon->phase_name();

if ($moonphasename == "New Moon"):  
....
elseif ($moonphasename == "Full Moon"):
....
```

I'm using this method because I have build a precise SVG drawing (from [this thread](https://stackoverflow.com/a/52950656)) of the moon according to the moon illumination : 

```
$mooncalc3 = $moon->get('illumination') - 0.5;
elseif ($moonphasename == "Waxing Gibbous"):  // Waxing Gibbous OK
     echo '
    <svg xmlns="http://www.w3.org/2000/svg" width="139" height="134">
      <defs>
        <mask id="phase-mask" maskContentUnits="objectBoundingBox">
          <rect x="0.5" y="0" width="0.5" height="1" fill="white"/>
          <ellipse id="phase-ellipse" cx="0.5" cy="0.5" rx="'.$mooncalc3.'" ry="0.5" fill="white"/>
        </mask>
      </defs>
      <circle fill="black" r="58" cy="69" cx="69"/><!-- moon shadow -->
      <circle fill="#fff" r="57.25" cy="69" cx="69" mask="url(#phase-mask)"/><!-- sunlight on moon -->
    </svg>';
    echo "<div>Lune: " . round($percent * 100, 1) . "&thinsp;%</div>";
```

Do you know a better way to check the phase name of the day ? Is it a bug ? 
Thanks

**Comment by solarissmoke** [comment]
Hi. Can you provide a specific example of where you think the phase is wrong - i.e., give a specific timestamp for which you get an incorrect result? To say there is "a day or two lag" is not specific enough to debug.

I'd also suggest you use the actual phase (`$moon->get('phase')`) instead of reverse-engineering this from the phase name. There are only 8 phase names, which means each phase lasts 3-4 days (which I suspect is where your issue is).

**Comment by culbrique** [comment]
Thanks for your reply.
I remember it was some days ago, on Thu, 12 Sep 2019 with  `date_default_timezone_set('Europe/Paris')` ( i don't know if this count).

```
$moonname = new Solaris\MoonPhase(strtotime(date('2019-09-12 12:00')));
echo $moonname->phase_name();
```

I get "Full Moon", but be were two days before the full moon, the 14 Sep 2019.
Of course I could eventually use `$moon->get('phase')`, but what is the correct statement to check every phases ? Do I have to round the value ?

**Comment by solarissmoke** [comment]
> I get "Full Moon", but be were two days before the full moon, the 14 Sep 2019.

This looks like expected and correct behaviour to me. There are 8 phase names, and each phase name occupies the 1/16th phase either side of it - i.e., "New Moon" occupies the 1/16th phases either side of phase = 0, and "Full Moon" occupies the 1/16th phases either side of phase = 1. This is what you're seeing - and is why I suggest you use the phase instead of the name.

> Of course I could eventually use $moon->get('phase'), but what is the correct statement to check every phases?

I don't understand the question, sorry. It really depends what you're trying to do. If you want to draw accurately the illuminated portion, then use `illumination` and ignore the phase name - it doesn't matter. If your code for displaying the image depends on the phase name, then you have to accept that you will get low granularity because there are only 8 possible phase names.

I'm going to close this issue as I'm fairly certain the calculations are correct - it's a question of how you want to use the data.
